[workspace]
members = ["lib"]
exclude = ["pages", "example"]

[package]
name = "pages-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pages"
path = "src/main.rs"

[dependencies]
include_dir = "0.7.4"
walkdir = "2.5.0"
toml_edit = "0.25.12"

[dependencies.clap]
version = "4.6.1"
default-features = false
features = ["derive", "std", "help"]

[dependencies.zip]
version = "8.6.0"
default-features = false
features = ["deflate"]
