[package]
name = "edgeone-js"
version = "0.1.0"
edition = "2024"

[lib]
name = "pages"
crate-type = ["cdylib"]

[dependencies]
pages = { path = "../../", package = "pages-rs" }
napi = { version = "3.8.6", features = ["async"] }
napi-derive = "3.5.5"
axum = { version = "0.8.9" }
tower = "0.5.3"
http = "1.4.0"
http-body = "1.0.1"
http-body-util = "0.1.3"
