[package]
name = "nodejs-stream"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pages = { workspace = true }
pages-rs = { workspace = true }
tokio = { workspace = true, features = ["net"] }
axum = { workspace = true }
napi = { workspace = true, features = ["async"] }
napi-derive = { workspace = true }
